version: '3.8'
services:
  reset_router:
    build: .
    environment:
      - ROUTER_IP=${ROUTER_IP}
      - ROUTER_USERNAME=${ROUTER_USERNAME}
      - ROUTER_PASSWORD=${ROUTER_PASSWORD}
      - API_KEY=${API_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./logs:/app/logs

