x-common-base: &common-base
  build:
    context: .
    args:
      POETRY_ENV: prod
  env_file: .env
  environment:
    - TZ=${TZ:-UTC}

services:
  # --------------------------------
  # Continuous Operation (Main Loop)
  # --------------------------------
  autopilot:
    <<: *common-base
    container_name: network_autopilot
    restart: unless-stopped

  # --------------------------------
  # On-Demand Execution (Manual Run)
  # --------------------------------
  manual_run:
    <<: *common-base
    container_name: network_autopilot_manual
    restart: "no"





# services:
#   # --------------------------------
#   # Continuous Operation (Main Loop)
#   # --------------------------------
#   autopilot:
#     container_name: network_autopilot
#     restart: unless-stopped

#   # --------------------------------
#   # On-Demand Execution (Manual Run)
#   # --------------------------------
#   manual_run:
#     container_name: network_autopilot_manual
#     restart: "no"





# services:
#   # -------------------------------------------------------------------
#   # Manual Testing Mode
#   # -------------------------------------------------------------------
#   app:
#     build: .
#     env_file: .env
#     container_name: network_autopilot_app
#     command: python -m network_autopilot.__main__
#     environment:
#       - PYTHONPATH=/app/src
#       - TZ=${TZ:-UTC}
#     volumes:
#       # Mount the current directory into the container at /app
#       - .:/app
#       # Mount the host API keys path (from .env) and mirror the local path inside the container
#       - ${GOOGLE_API_KEY_LOCAL}:${GOOGLE_API_KEY_DOCKER}:ro   # Dynamically mount based on .env
#     restart: unless-stopped   # Auto-restarts on reboot/failure unless manually stopped

#   # -------------------------------------------------------------------
#   # Scheduled Execution Mode
#   # -------------------------------------------------------------------
#   cron:
#     build: .
#     env_file: .env
#     container_name: network_autopilot_cron
#     command: >
#       sh -c "while true; do
#                python -m network_autopilot.__main__;
#                sleep 60;
#              done"
#     environment:
#       - PYTHONPATH=/app/src
#       - TZ=${TZ:-UTC}
#     volumes:
#       - .:/app
#       - ${GOOGLE_API_KEY_LOCAL}:${GOOGLE_API_KEY_DOCKER}:ro
#     restart: unless-stopped   # Auto-restarts on reboot/failure unless manually stopped
